services:
  - type: web
    name: passwordless-auth
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
